spring:
  profiles: default
datasource:
  url: jdbc:hsqldb:file:./hsqldb/database
  username: SA
  password:
  driverClassName: org.hsqldb.jdbcDriver
  defaultSchema:
  maxPoolSize: 10
  hibernate:
    hbm2ddl.method: create-drop
    show_sql: true
    format_sql: true
    dialect: org.hibernate.dialect.HSQLDialect
logging:
  level:
    it.melo:'DEBUG'
---
spring:
  profiles: prod
datasource:
  url: jdbc:mysql://localhost:3306/todolist
  username: user
  password: password
  driverClassName: com.mysql.jdbc.Driver
  defaultSchema:
  hibernate:
    hbm2ddl.method: update
    show_sql: true
    format_sql: true
    dialect: org.hibernate.dialect.MySQLDialect
